/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

/**
 *
 * @author sgort
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        jMenuItemAltaAlumnos = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMenuItemAltaMateria = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemFormRegistro = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jMAlumnos.setText("Alumnos");

        jMenuItemAltaAlumnos.setText("Agregar Alumno");
        jMenuItemAltaAlumnos.addActionListener(this::jMenuItemAltaAlumnosActionPerformed);
        jMAlumnos.add(jMenuItemAltaAlumnos);

        jMenuBar1.add(jMAlumnos);

        jMMateria.setText("Materia");

        jMenuItemAltaMateria.setText("Agregar Materia");
        jMenuItemAltaMateria.addActionListener(this::jMenuItemAltaMateriaActionPerformed);
        jMMateria.add(jMenuItemAltaMateria);

        jMenuBar1.add(jMMateria);

        jMenuRegistro.setText("Registro");

        jMenuItemFormRegistro.setText("Formulario");
        jMenuItemFormRegistro.addActionListener(this::jMenuItemFormRegistroActionPerformed);
        jMenuRegistro.add(jMenuItemFormRegistro);

        jMenuBar1.add(jMenuRegistro);

        jMenuSalir.setText("Salir");
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAltaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaAlumnosActionPerformed
        // TODO add your handling code here:
        AltaAlumno ventana = new AltaAlumno();
        jDesktopPane1.add(ventana);
        
        ventana.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemAltaAlumnosActionPerformed

    private void jMenuItemAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaMateriaActionPerformed
        // TODO add your handling code here:
         AltaMateria ventana = new AltaMateria();
        jDesktopPane1.add(ventana);
        
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemAltaMateriaActionPerformed

    private void jMenuItemFormRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormRegistroActionPerformed
        // TODO add your handling code here:
         FormularioInscripcion ventana = new FormularioInscripcion();
        jDesktopPane1.add(ventana);
        
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemFormRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAltaAlumnos;
    private javax.swing.JMenuItem jMenuItemAltaMateria;
    private javax.swing.JMenuItem jMenuItemFormRegistro;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
